apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-watch-demo
resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- https-redirect.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/hraedon/cert-watch
  newName: ghcr.io/hraedon/cert-watch
  newTag: e4f2d2d
  digest: sha256:6b92c8f06d6b1eb1ca1da4fb8e933b109fe7f91278d05630bd73050f302a0f46
