apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-watch-demo
resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- https-redirect.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/hraedon/cert-watch
  newName: ghcr.io/hraedon/cert-watch
  newTag: bea04a5
  digest: sha256:913df8ba8d29c8a79afe5d8640fa9170b91c7271011ca10375119485305a63f4
