apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-watch-demo
resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- https-redirect.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/hraedon/cert-watch
  newName: ghcr.io/hraedon/cert-watch
  newTag: f497278
  digest: sha256:0c747c4fd7a1d5ef7ba50fbbf85023f1f5dbe21a64f54098c93c4963559fd59e
