apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-watch-demo
  namespace: cert-watch-demo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cert-watch-demo
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cert-watch-demo
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - port: http
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - ports:
        - port: 443
          protocol: TCP
    - ports:
        - port: 587
          protocol: TCP
        - port: 465
          protocol: TCP
        - port: 25
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 172.16.0.0/12
        - ipBlock:
            cidr: 192.168.0.0/16
        - ipBlock:
            cidr: fc00::/7
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 169.254.0.0/16
