apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-watch
resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- prometheus-rules.yaml
- networkpolicy.yaml
- https-redirect.yaml
- poddisruptionbudget.yaml
images:
- name: ghcr.io/hraedon/cert-watch
  newName: ghcr.io/hraedon/cert-watch
  newTag: 565807e
  digest: sha256:ea0c114cc21515e09b7a1ec139ae0c6d2fe480647f870ccbb981490c88f27c5d
