apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-watch
resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- prometheus-rules.yaml
- networkpolicy.yaml
- https-redirect.yaml
- poddisruptionbudget.yaml
images:
- name: ghcr.io/hraedon/cert-watch
  newName: ghcr.io/hraedon/cert-watch
  newTag: dce2380
  digest: sha256:b9393878d2196016bd909f8a24e2a33d76e8ce28ae0d65271025295959274ab1
