apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-watch
resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- prometheus-rules.yaml
- networkpolicy.yaml
- https-redirect.yaml
- poddisruptionbudget.yaml
images:
- name: ghcr.io/hraedon/cert-watch
  newName: ghcr.io/hraedon/cert-watch
  newTag: c1e5885
  digest: sha256:5b5e92023aeba07e044e0d3b843680d92323fd306ec05d008b53cbed9e082587
