apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-watch-data
  namespace: cert-watch
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
