"""Authorization guards: the FastAPI dependencies that decide whether a
request may proceed, plus the template-facing permission context."""

from __future__ import annotations

import logging
from collections.abc import Callable
from typing import Any, Literal, NoReturn
from urllib.parse import quote

from fastapi import FastAPI, Request
from fastapi.exceptions import HTTPException
from fastapi.responses import RedirectResponse
from starlette.responses import Response

from cert_watch.auth import SESSION_COOKIE
from cert_watch.auth.rbac import AuthContext
from cert_watch.auth.request_context import (
    SessionUser,
    _is_auth_enabled,
    resolve_session_user,
)
from cert_watch.security import _request_security
from cert_watch.security.csrf import check_csrf

logger = logging.getLogger("cert_watch.middleware")


def get_auth_context(request: Request) -> dict[str, Any]:
    """Return template context dict with auth_user, may_write, etc.

    When an AuthContext is present (Plan 035 RBAC), may_write is
    derived from AuthContext permissions.  Otherwise the legacy
    write_users / admin_users logic is used.
    """
    username = request.scope.get("auth_user", "")
    auth_ctx = getattr(request.state, "auth_context", None)

    may_write = auth_ctx.may_write() if auth_ctx is not None else _may_write(request, username)

    # Detect whether the local admin password is auto-generated
    settings = getattr(request.app.state, "settings", None)
    autogenerated = False
    if settings:
        from cert_watch.config import LOCAL_ADMIN_AUTOGENERATED
        from cert_watch.database import kv_get
        val = kv_get(settings.db_path, LOCAL_ADMIN_AUTOGENERATED)
        autogenerated = val is not None and val == "1"

    # Plan 040: resolve user email from session or DB
    user_email = ""
    if auth_ctx:
        user_email = getattr(auth_ctx, "email", "")
    if not user_email and settings:
        try:
            from cert_watch.auth.session import decode_session
            from cert_watch.database.users_roles import SqliteUserRepository

            token = request.cookies.get(SESSION_COOKIE, "")
            info = decode_session(token, _request_security(request))
            if info and info.email:
                user_email = info.email
            else:
                user_repo = SqliteUserRepository(settings.db_path)
                user = user_repo.get_by_username(username)
                if user:
                    user_email = user.email
        except Exception:
            logger.debug("failed to resolve user email for %s", username, exc_info=True)

    no_auth = not _is_auth_enabled(request)
    is_admin = (
        auth_ctx.is_admin if auth_ctx is not None else no_auth
    )

    return {
        "auth_user": username,
        "may_write": may_write,
        "is_admin": is_admin,
        "local_admin_autogenerated": autogenerated,
        "user_email": user_email,
        "scope_tag": getattr(auth_ctx, "scope_tag", "") if auth_ctx else "",
        "permission_tier": getattr(auth_ctx, "tier", "") if auth_ctx else "",
    }


def _may_write(request: Request, username: str) -> bool:
    """Return True if *username* is allowed to perform mutations.

    Uses the legacy write_users/admin_users lists only — RBAC is handled
    by the caller (``_write_denied``) through the AuthContext.
    """
    if not _is_auth_enabled(request):
        return True
    settings = getattr(request.app.state, "settings", None)
    if not settings:
        return False
    if not settings.write_users:
        return True
    if username in settings.write_users:
        return True
    return username in settings.admin_users


def _write_denied(request: Request, username: str) -> bool:
    """Return True if *username* must be denied write access.

    Single source of truth for the write decision shared by ``write_guard``
    (API, raises) and ``write_form_guard`` (HTML forms, redirects), so the
    two paths cannot diverge. When a role map is configured (Plan 035 RBAC),
    the request's AuthContext permissions decide; otherwise the legacy
    write_users/admin_users lists apply. A missing AuthContext under the
    role-map or API-key paths is treated as deny-by-default.
    """
    # API-key auth (Plan 039) always carries an explicit scope-derived
    # AuthContext, so its scope governs regardless of whether a role map is set
    # — otherwise a read-scoped key could write when no role map is configured.
    if getattr(request.state, "api_key_auth", False):
        api_ctx: AuthContext | None = getattr(request.state, "auth_context", None)
        return api_ctx is None or not api_ctx.may_write()
    settings = getattr(request.app.state, "settings", None)
    role_map = getattr(settings, "role_map", {}) if settings else {}
    auth_ctx: AuthContext | None = getattr(request.state, "auth_context", None)
    # A local account's role is authoritative with or without a role map.
    if role_map or (auth_ctx is not None and auth_ctx.local_account):
        # Plan 053: a user whose only write grants are per-tag tiers passes
        # this gate; the per-resource decision happens at the scope seam
        # (routes/_scoped.py:scope_write_denied via may_write_tags).
        return auth_ctx is None or not auth_ctx.may_write_any()
    return not _may_write(request, username)


def _admin_redirect_target(request: Request) -> str:
    """Return a sensible redirect URL for admin-form failures.

    Settings POSTs should bounce back to the settings page; other admin
    routes can pass their own via the helper. Falls back to ``/`` when the
    route is unknown.
    """
    path = request.url.path
    if path.startswith("/settings"):
        return "/settings"
    return "/"


def _admin_allowed(request: Request, user: str, *, use_legacy: bool = False) -> bool:
    """Check whether *user* may perform admin actions.

    The legacy ``admin_users`` list is an explicit allowlist only — an empty
    list never grants admin (fail-closed), so a misconfigured deployment
    cannot silently widen admin access.
    """
    settings = getattr(request.app.state, "settings", None)
    role_map = getattr(settings, "role_map", {}) if settings else {}
    ctx: AuthContext | None = getattr(request.state, "auth_context", None)
    if role_map or not use_legacy or (ctx is not None and ctx.local_account):
        return ctx is not None and ctx.is_admin
    admin_ok = ctx is not None and ctx.is_admin
    if not admin_ok:
        admin_list = getattr(settings, "admin_users", None) if settings else None
        if admin_list and user in admin_list:
            admin_ok = True
    return admin_ok



def _check_auth(
    request: Request,
    *,
    resolve_session: bool = True,
    require_write: bool = False,
    require_admin: bool = False,
    admin_legacy: bool = False,
) -> SessionUser:
    if not _is_auth_enabled(request):
        request.state.auth_context = AuthContext.system()
        return SessionUser(user="")

    if resolve_session:
        result = resolve_session_user(request)
        user = result.user
        api_key_auth = result.api_key_auth
        error = result.error
    else:
        user = request.scope.get("auth_user")
        api_key_auth = getattr(request.state, "api_key_auth", False)
        error = None

    if error:
        return SessionUser(error=error)
    if not user:
        return SessionUser(error="unauthenticated")

    if require_write and _write_denied(request, user):
        return SessionUser(user=user, error="read-only user")
    if require_admin and not _admin_allowed(request, user, use_legacy=admin_legacy):
        return SessionUser(user=user, error="admin required")

    return SessionUser(user=user, api_key_auth=api_key_auth)


async def _csrf_required_error(request: Request) -> str | None:
    if getattr(request.state, "api_key_auth", False):
        return None
    return await check_csrf(request)


# ---------- the guard family ----------
#
# Every route declares its requirement as ONE dependency from this family:
#
#   read (no CSRF; refused on a mutating route by tests/test_route_guards.py)
#     require_auth          JSON/any: authenticated, else 401
#     require_admin         JSON: admin, else 401/403
#     admin_page_guard      HTML page: admin, else redirect
#     require_admin_session / admin_session_page_guard
#                           API-key management: admin browser session only
#
#   mutation (CSRF built in -- there is no way to construct one without it)
#     write_guard           JSON write: 401/403, CSRF 403
#     admin_write_guard     JSON admin: 401/403, CSRF 403
#     json_write_guard / admin_json_write_guard
#                           JSON-body variants requiring application/json
#     admin_session_*       API-key management: admin browser session only
#     write_form_guard      HTML form write: redirect on refusal
#     admin_form_guard      HTML form admin: redirect on refusal
#     admin_settings_form(bounce)   Settings forms: admin, CSRF failure
#                           bounces back to the settings tab
#
# An HTML guard cannot *return* a redirect from a dependency, so it raises
# GuardRejection carrying the response; ``install_guard_handler`` registers
# the handler that sends it.


class GuardRejection(Exception):
    """An HTML guard refused the request; ``response`` is what the client gets."""

    def __init__(self, response: Response) -> None:
        super().__init__(response.status_code)
        self.response = response


async def _guard_rejection_handler(request: Request, exc: Exception) -> Response:
    assert isinstance(exc, GuardRejection)
    return exc.response


def install_guard_handler(application: FastAPI) -> None:
    """Let HTML guards refuse with a redirect (see :class:`GuardRejection`)."""
    application.add_exception_handler(GuardRejection, _guard_rejection_handler)


def _bounce(base: str, message: str) -> RedirectResponse:
    sep = "&" if "?" in base else "?"
    return RedirectResponse(url=f"{base}{sep}error={quote(message)}", status_code=303)


def _login_redirect() -> GuardRejection:
    return GuardRejection(RedirectResponse(url="/login", status_code=303))


def _raise_json(error: str) -> NoReturn:
    if error == "unauthenticated":
        raise HTTPException(status_code=401, detail="unauthenticated")
    raise HTTPException(status_code=403, detail=error)


# A CSRF failure on an HTML form: a bounce URL (``?error=`` is appended) or a
# callable building the response (e.g. re-rendering the page with the error).
CsrfFailure = str | Callable[[Request, str], Response]


class ReadGuard:
    """Authentication, optionally admin. No CSRF check, so read routes only."""

    def __init__(self, *, admin: bool, form: bool, session_only: bool = False) -> None:
        self.admin = admin
        self.form = form
        self.session_only = session_only

    def __repr__(self) -> str:
        return (
            f"ReadGuard(admin={self.admin}, form={self.form}, "
            f"session_only={self.session_only})"
        )

    async def __call__(self, request: Request) -> str:
        if not self.form:
            result = _check_auth(request, require_admin=self.admin)
            if result.error:
                _raise_json(result.error if self.admin else "unauthenticated")
            if self.session_only and result.api_key_auth:
                raise HTTPException(status_code=403, detail="admin browser session required")
            return result.user or ""
        # HTML page (admin only in practice): relies on auth_middleware having
        # authenticated the request; the legacy CERT_WATCH_ADMINS list applies.
        if not _is_auth_enabled(request):
            _check_auth(request, resolve_session=False, require_admin=self.admin)
            return ""
        result = _check_auth(
            request, resolve_session=False, require_admin=self.admin, admin_legacy=True,
        )
        if result.error:
            if result.error == "unauthenticated":
                raise _login_redirect()
            raise GuardRejection(_bounce(_admin_redirect_target(request), result.error))
        if self.session_only and getattr(request.state, "api_key_auth", False):
            raise GuardRejection(
                _bounce(_admin_redirect_target(request), "admin browser session required")
            )
        return result.user or ""


class MutationGuard:
    """A write- or admin-level guard for a state-changing route.

    CSRF is part of every mutation guard and cannot be switched off: the
    constructor only chooses *how a CSRF failure is reported*. API-key
    (bearer) requests carry no ambient cookie credential and are exempt,
    except on ``browser_only`` forms, which hold them to the check -- and so
    refuse them -- exactly like a cookie request without a token.

    JSON guards raise 401/403. They check CSRF whenever authentication is
    configured and for cookie-carrying/browser requests in open mode. HTML
    form guards redirect and check CSRF always.
    """

    def __init__(
        self,
        level: Literal["write", "admin"],
        *,
        form: bool,
        csrf_failure: CsrfFailure | None = None,
        browser_only: bool = False,
        json_only: bool = False,
        session_only: bool = False,
    ) -> None:
        if level not in ("write", "admin"):
            raise ValueError(f"unknown guard level {level!r}")
        if not form and (csrf_failure is not None or browser_only):
            raise ValueError("csrf_failure / browser_only apply to HTML form guards only")
        if form and json_only:
            raise ValueError("json_only applies to JSON guards only")
        self.level = level
        self.form = form
        self.csrf_failure = csrf_failure
        self.browser_only = browser_only
        self.json_only = json_only
        self.session_only = session_only

    def __repr__(self) -> str:
        return (
            f"MutationGuard({self.level!r}, form={self.form}, "
            f"csrf_failure={self.csrf_failure!r}, browser_only={self.browser_only}, "
            f"json_only={self.json_only}, session_only={self.session_only})"
        )

    async def _csrf_error(self, request: Request) -> str | None:
        if self.browser_only:
            return await check_csrf(request)
        return await _csrf_required_error(request)

    async def __call__(self, request: Request) -> str:
        if self.form:
            return await self._form(request)
        if self.json_only:
            media_type = request.headers.get("content-type", "").split(";", 1)[0]
            if media_type.strip().lower() != "application/json":
                raise HTTPException(
                    status_code=415, detail="Content-Type must be application/json"
                )
        result = _check_auth(
            request,
            require_write=self.level == "write",
            require_admin=self.level == "admin",
        )
        if result.error:
            _raise_json(result.error)
        if self.session_only and result.api_key_auth:
            raise HTTPException(status_code=403, detail="admin browser session required")
        browser_request = bool(request.cookies) or any(
            header in request.headers for header in ("origin", "sec-fetch-site")
        )
        if _is_auth_enabled(request) or browser_request:
            csrf_err = await self._csrf_error(request)
            if csrf_err:
                raise HTTPException(status_code=403, detail=csrf_err)
        return result.user or ""

    async def _form(self, request: Request) -> str:
        user = ""
        if self.level == "write":
            error = form_write_error(request)
            if error:
                if error == "unauthenticated":
                    raise _login_redirect()
                raise GuardRejection(_bounce("/", error))
            user = request.scope.get("auth_user", "") or ""
            default_bounce = "/"
        else:
            if _is_auth_enabled(request):
                result = _check_auth(
                    request, resolve_session=False, require_admin=True, admin_legacy=True,
                )
                if result.error:
                    if result.error == "unauthenticated":
                        raise _login_redirect()
                    raise GuardRejection(
                        _bounce(_admin_redirect_target(request), result.error)
                    )
                user = result.user or ""
            else:
                _check_auth(request, resolve_session=False, require_admin=True)
            default_bounce = _admin_redirect_target(request)
        if self.session_only and getattr(request.state, "api_key_auth", False):
            raise GuardRejection(_bounce(default_bounce, "admin browser session required"))
        csrf_err = await self._csrf_error(request)
        if csrf_err:
            failure = self.csrf_failure or default_bounce
            if callable(failure):
                raise GuardRejection(failure(request, csrf_err))
            raise GuardRejection(_bounce(failure, csrf_err))
        return user


def admin_settings_form(
    csrf_failure: CsrfFailure, *, session_only: bool = False
) -> MutationGuard:
    """The guard for a Settings form POST: admin, browser-only, and a CSRF
    failure lands back on the settings tab the form came from."""
    return MutationGuard(
        "admin",
        form=True,
        csrf_failure=csrf_failure,
        browser_only=True,
        session_only=session_only,
    )


require_auth = ReadGuard(admin=False, form=False)
require_admin = ReadGuard(admin=True, form=False)
admin_page_guard = ReadGuard(admin=True, form=True)
require_admin_session = ReadGuard(admin=True, form=False, session_only=True)
admin_session_page_guard = ReadGuard(admin=True, form=True, session_only=True)
write_guard = MutationGuard("write", form=False)
admin_write_guard = MutationGuard("admin", form=False)
json_write_guard = MutationGuard("write", form=False, json_only=True)
admin_json_write_guard = MutationGuard("admin", form=False, json_only=True)
admin_session_write_guard = MutationGuard("admin", form=False, session_only=True)
admin_session_json_write_guard = MutationGuard(
    "admin", form=False, json_only=True, session_only=True
)


class MetricsGuard:
    """Authorize a metrics bearer token or an admin browser session."""

    async def __call__(self, request: Request) -> str:
        from cert_watch.auth.request_context import (
            check_metrics_token,
            metrics_token_configured,
        )

        token_configured = metrics_token_configured(request)
        if token_configured and check_metrics_token(request):
            return ""
        if token_configured and not _is_auth_enabled(request):
            raise HTTPException(status_code=401, detail="unauthorized")
        result = _check_auth(request, require_admin=True)
        if result.error:
            if result.error == "unauthenticated" and token_configured:
                raise HTTPException(status_code=401, detail="unauthorized")
            _raise_json(result.error)
        if result.api_key_auth:
            raise HTTPException(status_code=403, detail="admin browser session required")
        return result.user or ""


metrics_guard = MetricsGuard()
write_form_guard = MutationGuard("write", form=True)
admin_form_guard = MutationGuard("admin", form=True)


def form_write_error(request: Request) -> str | None:
    """Why ``write_form_guard`` would refuse this request, or None if it would not.

    Everything that gate decides except CSRF, which needs the request body and
    is not a property of the user. Exported so a template can ask the exact
    question the POST will answer, instead of approximating it.

    ``_write_denied`` calls itself the single source of truth for the write
    decision, and for the two gates that use it that is so. A third caller --
    the settings-form affordance in ``routes/hosts.py`` -- reached past it to
    ``AuthContext.may_write_any()``, which is a *different* predicate: an
    API-key context is judged on ``may_write()``, and the legacy path on the
    ``write_users`` list, so a user with only per-tag write grants was shown a
    form the POST then refused, discarding what they had typed (#32). Asking
    one question in two vocabularies is how an affordance drifts from its gate;
    this makes the template's question the gate's own.

    Note: under disabled auth this installs the open ``AuthContext`` exactly as
    the request path would, so calling it during a render is idempotent.
    """
    return _check_auth(request, resolve_session=False, require_write=True).error
