"""Authorization guards: the FastAPI dependencies that decide whether a
request may proceed, plus the template-facing permission context."""

from __future__ import annotations

import logging
from typing import Any
from urllib.parse import quote

from fastapi import Request
from fastapi.exceptions import HTTPException
from fastapi.responses import RedirectResponse

from cert_watch.auth import SESSION_COOKIE
from cert_watch.auth.rbac import AuthContext
from cert_watch.auth.request_context import (
    SessionUser,
    _is_auth_enabled,
    resolve_session_user,
)
from cert_watch.security import _request_security
from cert_watch.security.csrf import check_csrf

logger = logging.getLogger("cert_watch.middleware")


def get_auth_context(request: Request) -> dict[str, Any]:
    """Return template context dict with auth_user, may_write, etc.

    When an AuthContext is present (Plan 035 RBAC), may_write is
    derived from AuthContext permissions.  Otherwise the legacy
    write_users / admin_users logic is used.
    """
    username = request.scope.get("auth_user", "")
    auth_ctx = getattr(request.state, "auth_context", None)

    may_write = auth_ctx.may_write() if auth_ctx is not None else _may_write(request, username)

    # Detect whether the local admin password is auto-generated
    settings = getattr(request.app.state, "settings", None)
    autogenerated = False
    if settings:
        from cert_watch.config import LOCAL_ADMIN_AUTOGENERATED
        from cert_watch.database import kv_get
        val = kv_get(settings.db_path, LOCAL_ADMIN_AUTOGENERATED)
        autogenerated = val is not None and val == "1"

    # Plan 040: resolve user email from session or DB
    user_email = ""
    if auth_ctx:
        user_email = getattr(auth_ctx, "email", "")
    if not user_email and settings:
        try:
            from cert_watch.auth.session import decode_session
            from cert_watch.database.users_roles import SqliteUserRepository

            token = request.cookies.get(SESSION_COOKIE, "")
            info = decode_session(token, _request_security(request))
            if info and info.email:
                user_email = info.email
            else:
                user_repo = SqliteUserRepository(settings.db_path)
                user = user_repo.get_by_username(username)
                if user:
                    user_email = user.email
        except Exception:
            logger.debug("failed to resolve user email for %s", username, exc_info=True)

    no_auth = not _is_auth_enabled(request)
    is_admin = (
        auth_ctx.is_admin if auth_ctx is not None else no_auth
    )

    return {
        "auth_user": username,
        "may_write": may_write,
        "is_admin": is_admin,
        "local_admin_autogenerated": autogenerated,
        "user_email": user_email,
        "scope_tag": getattr(auth_ctx, "scope_tag", "") if auth_ctx else "",
        "permission_tier": getattr(auth_ctx, "tier", "") if auth_ctx else "",
    }


def _may_write(request: Request, username: str) -> bool:
    """Return True if *username* is allowed to perform mutations.

    Uses the legacy write_users/admin_users lists only — RBAC is handled
    by the caller (``require_write``) through the AuthContext.
    """
    if not _is_auth_enabled(request):
        return True
    settings = getattr(request.app.state, "settings", None)
    if not settings:
        return False
    if not settings.write_users:
        return True
    if username in settings.write_users:
        return True
    return username in settings.admin_users


def _write_denied(request: Request, username: str) -> bool:
    """Return True if *username* must be denied write access.

    Single source of truth for the write decision shared by ``require_write``
    (API, raises) and ``require_write_form`` (HTML forms, redirects), so the
    two paths cannot diverge. When a role map is configured (Plan 035 RBAC),
    the request's AuthContext permissions decide; otherwise the legacy
    write_users/admin_users lists apply. A missing AuthContext under the
    role-map or API-key paths is treated as deny-by-default.
    """
    # API-key auth (Plan 039) always carries an explicit scope-derived
    # AuthContext, so its scope governs regardless of whether a role map is set
    # — otherwise a read-scoped key could write when no role map is configured.
    if getattr(request.state, "api_key_auth", False):
        api_ctx: AuthContext | None = getattr(request.state, "auth_context", None)
        return api_ctx is None or not api_ctx.may_write()
    settings = getattr(request.app.state, "settings", None)
    role_map = getattr(settings, "role_map", {}) if settings else {}
    auth_ctx: AuthContext | None = getattr(request.state, "auth_context", None)
    # A local account's role is authoritative with or without a role map.
    if role_map or (auth_ctx is not None and auth_ctx.local_account):
        # Plan 053: a user whose only write grants are per-tag tiers passes
        # this gate; the per-resource decision happens at the scope seam
        # (routes/_scoped.py:scope_write_denied via may_write_tags).
        return auth_ctx is None or not auth_ctx.may_write_any()
    return not _may_write(request, username)


def _admin_redirect_target(request: Request) -> str:
    """Return a sensible redirect URL for admin-form failures.

    Settings POSTs should bounce back to the settings page; other admin
    routes can pass their own via the helper. Falls back to ``/`` when the
    route is unknown.
    """
    path = request.url.path
    if path.startswith("/settings"):
        return "/settings"
    return "/"


def _admin_allowed(request: Request, user: str, *, use_legacy: bool = False) -> bool:
    """Check whether *user* may perform admin actions.

    The legacy ``admin_users`` list is an explicit allowlist only — an empty
    list never grants admin (fail-closed), so a misconfigured deployment
    cannot silently widen admin access.
    """
    settings = getattr(request.app.state, "settings", None)
    role_map = getattr(settings, "role_map", {}) if settings else {}
    ctx: AuthContext | None = getattr(request.state, "auth_context", None)
    if role_map or not use_legacy or (ctx is not None and ctx.local_account):
        return ctx is not None and ctx.is_admin
    admin_ok = ctx is not None and ctx.is_admin
    if not admin_ok:
        admin_list = getattr(settings, "admin_users", None) if settings else None
        if admin_list and user in admin_list:
            admin_ok = True
    return admin_ok



def _check_auth(
    request: Request,
    *,
    resolve_session: bool = True,
    require_write: bool = False,
    require_admin: bool = False,
    admin_legacy: bool = False,
) -> SessionUser:
    if not _is_auth_enabled(request):
        request.state.auth_context = AuthContext.full_access("")
        return SessionUser(user="")

    if resolve_session:
        result = resolve_session_user(request)
        user = result.user
        api_key_auth = result.api_key_auth
        error = result.error
    else:
        user = request.scope.get("auth_user")
        api_key_auth = getattr(request.state, "api_key_auth", False)
        error = None

    if error:
        return SessionUser(error=error)
    if not user:
        return SessionUser(error="unauthenticated")

    if require_write and _write_denied(request, user):
        return SessionUser(user=user, error="read-only user")
    if require_admin and not _admin_allowed(request, user, use_legacy=admin_legacy):
        return SessionUser(user=user, error="admin required")

    return SessionUser(user=user, api_key_auth=api_key_auth)


async def _csrf_required_error(request: Request) -> str | None:
    if getattr(request.state, "api_key_auth", False):
        return None
    return await check_csrf(request)


async def require_auth(request: Request) -> str:
    """FastAPI dependency. Returns username or raises 401."""
    result = _check_auth(request)
    if result.error:
        raise HTTPException(status_code=401, detail="unauthenticated")
    return result.user or ""


async def require_write(request: Request) -> str:
    """Auth + CSRF + write_users check. Returns username or raises 401/403."""
    result = _check_auth(request, require_write=True)
    if result.error:
        if result.error == "unauthenticated":
            raise HTTPException(status_code=401, detail="unauthenticated")
        raise HTTPException(status_code=403, detail=result.error)
    if _is_auth_enabled(request):
        csrf_err = await _csrf_required_error(request)
        if csrf_err:
            raise HTTPException(status_code=403, detail=csrf_err)
    return result.user or ""


async def require_admin(request: Request) -> str:
    """Auth + admin-permission check (no CSRF). Use for admin-scoped GETs."""
    result = _check_auth(request, require_admin=True)
    if result.error:
        if result.error == "unauthenticated":
            raise HTTPException(status_code=401, detail="unauthenticated")
        raise HTTPException(status_code=403, detail=result.error)
    return result.user or ""


async def require_admin_write(request: Request) -> str:
    """``require_admin`` + CSRF (skipped for API-key auth). Use for admin mutations."""
    result = _check_auth(request, require_admin=True)
    if result.error:
        if result.error == "unauthenticated":
            raise HTTPException(status_code=401, detail="unauthenticated")
        raise HTTPException(status_code=403, detail=result.error)
    if _is_auth_enabled(request):
        csrf_err = await _csrf_required_error(request)
        if csrf_err:
            raise HTTPException(status_code=403, detail=csrf_err)
    return result.user or ""


def require_admin_form(request: Request) -> RedirectResponse | None:
    """Form-POST helper: admin-only check (no CSRF), redirect on failure."""
    if not _is_auth_enabled(request):
        return None
    result = _check_auth(
        request, resolve_session=False, require_admin=True, admin_legacy=True,
    )
    if result.error:
        if result.error == "unauthenticated":
            return RedirectResponse(url="/login", status_code=303)
        return RedirectResponse(
            url=f"{_admin_redirect_target(request)}?error={quote(result.error)}",
            status_code=303,
        )
    return None


def form_write_error(request: Request) -> str | None:
    """Why ``require_write_form`` would refuse this request, or None if it would not.

    Everything that gate decides except CSRF, which needs the request body and
    is not a property of the user. Exported so a template can ask the exact
    question the POST will answer, instead of approximating it.

    ``_write_denied`` calls itself the single source of truth for the write
    decision, and for the two gates that use it that is so. A third caller --
    the settings-form affordance in ``routes/hosts.py`` -- reached past it to
    ``AuthContext.may_write_any()``, which is a *different* predicate: an
    API-key context is judged on ``may_write()``, and the legacy path on the
    ``write_users`` list, so a user with only per-tag write grants was shown a
    form the POST then refused, discarding what they had typed (#32). Asking
    one question in two vocabularies is how an affordance drifts from its gate;
    this makes the template's question the gate's own.

    Note: under disabled auth this installs the open ``AuthContext`` exactly as
    the request path would, so calling it during a render is idempotent.
    """
    return _check_auth(request, resolve_session=False, require_write=True).error


async def require_write_form(request: Request) -> RedirectResponse | None:
    """Form-POST helper: check write access + CSRF, return redirect on failure."""
    error = form_write_error(request)
    if error:
        if error == "unauthenticated":
            return RedirectResponse(url="/login", status_code=303)
        return RedirectResponse(url=f"/?error={quote(error)}", status_code=303)
    csrf_err = await _csrf_required_error(request)
    if csrf_err:
        return RedirectResponse(url=f"/?error={quote(csrf_err)}", status_code=303)
    return None


async def require_admin_write_form(request: Request) -> RedirectResponse | None:
    """Form-POST helper: admin + write + CSRF check, redirect on failure."""
    result = _check_auth(
        request, resolve_session=False, require_admin=True, admin_legacy=True,
    )
    if result.error:
        if result.error == "unauthenticated":
            return RedirectResponse(url="/login", status_code=303)
        return RedirectResponse(
            url=f"{_admin_redirect_target(request)}?error={quote(result.error)}",
            status_code=303,
        )
    csrf_err = await _csrf_required_error(request)
    if csrf_err:
        return RedirectResponse(
            url=f"{_admin_redirect_target(request)}?error={quote(csrf_err)}",
            status_code=303,
        )
    return None

