"""Ratchet: every CSS class referenced in Jinja2 templates must exist in CSS.

A utility class that isn't in tokens.css silently does nothing — no console
error, no visual cue. This has been a recurring bug class (e.g. cw-gap-9 /
cw-gap-14 referenced for months while undefined). This test prevents new
instances by ensuring all static class references in templates resolve to a
defined CSS selector.

Dynamic classes (Jinja2 expressions like ``{{ urg }}``) are excluded from the
check since their values depend on runtime data.

To fix a violation: either add the missing class to tokens.css (or the
page-local ``<style>`` block), or update the template to use an existing
class.  If the class is a JS-only state marker (never styled), add it to
``_WHITELIST``.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSS_DIR = ROOT / "src" / "cert_watch" / "static" / "css"
TEMPLATES_DIR = ROOT / "src" / "cert_watch" / "templates"

_CSS_CLASS_RE = re.compile(r"\.([a-zA-Z_][a-zA-Z0-9_-]*)")
_CLASS_ATTR_RE = re.compile(r'''class\s*=\s*"([^"]*)"''')
_CLASSNAME_RE = re.compile(r"""\.className\s*=\s*['"]([^'"]*?)['"]""")
_CLASSLIST_RE = re.compile(r"""classList\.\w+\(\s*['"]([^'"]*)['"]""")
_SCRIPT_RE = re.compile(r"<script[^>]*>(.*?)</script>", re.DOTALL)
_JINJA_TAG_RE = re.compile(r"\{\{.*?\}\}|\{%.*?%\}")
_JINJA_COMMENT_RE = re.compile(r"\{#.*?#\}", re.DOTALL)
_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
_CSS_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
_JS_SQ_RE = re.compile(r"'([^']*)'")
_JS_DQ_RE = re.compile(r'"([^"]*)"')

_WHITELIST = frozenset({
    "confirm-form",
    "tab-body",
    "cw-loaded",
    "cw-autogenerated-banner",
    "cw-health-dismissed",
    "cw-health-text",
    "cw-theme",
    "cw-note-chip",
    "cw-note-inline-form",
})


def _extract_css_classes() -> set[str]:
    classes: set[str] = set()
    for css_file in CSS_DIR.rglob("*.css"):
        content = css_file.read_text(encoding="utf-8")
        content = _CSS_COMMENT_RE.sub("", content)
        for m in _CSS_CLASS_RE.finditer(content):
            classes.add(m.group(1))

    for tpl in TEMPLATES_DIR.rglob("*.html"):
        content = tpl.read_text(encoding="utf-8")
        for block in re.findall(r"<style>(.*?)</style>", content, re.DOTALL):
            block = _CSS_COMMENT_RE.sub("", block)
            for m in _CSS_CLASS_RE.finditer(block):
                classes.add(m.group(1))

    return classes


def _extract_template_classes() -> set[tuple[str, str]]:
    found: set[tuple[str, str]] = set()
    for tpl in sorted(TEMPLATES_DIR.rglob("*.html")):
        content = tpl.read_text(encoding="utf-8")
        content = _JINJA_COMMENT_RE.sub("", content)
        content = _HTML_COMMENT_RE.sub("", content)

        scripts = _SCRIPT_RE.findall(content)
        html_only = _SCRIPT_RE.sub("", content)

        for m in _CLASS_ATTR_RE.finditer(html_only):
            value = _JINJA_TAG_RE.sub(" ", m.group(1))
            for cls in value.split():
                if cls:
                    found.add((tpl.name, cls))

        for script in scripts:
            for str_m in _JS_SQ_RE.finditer(script):
                _scan_js_literal(str_m.group(1), tpl.name, found)
            for str_m in _JS_DQ_RE.finditer(script):
                _scan_js_literal(str_m.group(1), tpl.name, found)

            for m in _CLASSNAME_RE.finditer(script):
                for cls in m.group(1).split():
                    if cls:
                        found.add((tpl.name, cls))

            for m in _CLASSLIST_RE.finditer(script):
                cls = m.group(1).strip()
                if cls:
                    found.add((tpl.name, cls))

    return found


def _clean_token(token: str) -> str:
    end = len(token)
    for i, ch in enumerate(token):
        if ch not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-":
            end = i
            break
    return token[:end]


def _scan_js_literal(literal: str, tpl_name: str, found: set[tuple[str, str]]) -> None:
    for cls_m in _CLASS_ATTR_RE.finditer(literal):
        for cls in cls_m.group(1).split():
            cls = _clean_token(cls)
            if cls:
                found.add((tpl_name, cls))
    for token in literal.split():
        token = _clean_token(token)
        if token.startswith("cw-") and not token.endswith("-"):
            found.add((tpl_name, token))


def _should_check(name: str) -> bool:
    if not name or name in _WHITELIST:
        return False
    return not (name.endswith("-") or name.startswith("-"))


def test_css_class_coverage():
    css_classes = _extract_css_classes()
    template_classes = _extract_template_classes()

    violations = []
    for tpl_name, cls in sorted(template_classes):
        if not _should_check(cls):
            continue
        if cls not in css_classes:
            violations.append((tpl_name, cls))

    assert not violations, (
        "Undefined CSS classes found in templates. "
        "Add the class to tokens.css or whitelist it in this test.\n"
        + "\n".join(f"  {tpl}: .{cls}" for tpl, cls in violations)
    )
