"""Tests for secure-by-default auth posture (BC-083) and fail-closed fallback."""

from __future__ import annotations

import asyncio

import pytest

from cert_watch.config import (
    LOCAL_ADMIN_AUTOGENERATED,
    LOCAL_ADMIN_PASSWORD_HASH,
    LOCAL_ADMIN_USER,
    SETUP_COMPLETE,
    Settings,
)
from cert_watch.database import kv_get
from cert_watch.database.kv_store import kv_all, kv_set_multi


def _drive_lifespan(app) -> None:
    """Enter and cleanly exit the app's real lifespan once.

    Exercises the actual ``cert_watch.app`` startup path (BC-083 check,
    scheduler start/stop) rather than re-implementing its boolean. Raises
    whatever the lifespan raises (e.g. SystemExit).
    """

    async def _run() -> None:
        async with app.router.lifespan_context(app):
            pass

    asyncio.run(_run())


def _clean_env(monkeypatch, tmp_path) -> None:
    """Strip ambient auth/host config so each test controls the inputs."""
    for var in (
        "AUTH_PROVIDER",
        "CERT_WATCH_ALLOW_UNAUTH",
        "CERT_WATCH_HOST",
        "CERT_WATCH_TRUST_PROXY",
        "CERT_WATCH_AUTH_SECRET",
        "CERT_WATCH_CSRF_SECRET",
        "CERT_WATCH_LOCAL_ADMIN_USER",
        "CERT_WATCH_LOCAL_ADMIN_PASSWORD_HASH",
    ):
        monkeypatch.delenv(var, raising=False)
    monkeypatch.setenv("CERT_WATCH_DATA_DIR", str(tmp_path))


class TestSecureByDefault:
    """Drive the *real* lifespan (cert_watch.app) — not a replica of its boolean.
    First-run posture: a network-exposed instance with no auth auto-provisions a
    local admin (comes up authenticated); bare loopback dev stays open + /setup;
    ALLOW_UNAUTH forces open; provisioning failure on an exposed bind fails closed."""

    def test_autoprovisions_admin_on_nonloopback_no_auth(self, tmp_path, monkeypatch):
        """No auth + routable bind => auto-provision a local admin and start."""
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "0.0.0.0")

        app = create_app()
        _drive_lifespan(app)  # must not raise

        from cert_watch.auth import LocalAdminProvider, NoAuthProvider

        assert isinstance(app.state.auth_provider, LocalAdminProvider)
        assert not isinstance(app.state.auth_provider, NoAuthProvider)
        assert kv_get(tmp_path / "cert-watch.sqlite3", "local_admin_user") == "admin"
        assert kv_get(tmp_path / "cert-watch.sqlite3", "local_admin_autogenerated") == "1"
        assert (tmp_path / "initial-admin-password").exists()

    def test_autoprovisions_behind_proxy_on_loopback(self, tmp_path, monkeypatch):
        """Loopback + TRUST_PROXY=1 (IIS/nginx) is network-exposed => provision."""
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "127.0.0.1")
        monkeypatch.setenv("CERT_WATCH_TRUST_PROXY", "1")

        app = create_app()
        _drive_lifespan(app)

        from cert_watch.auth import LocalAdminProvider

        assert isinstance(app.state.auth_provider, LocalAdminProvider)
        assert (tmp_path / "initial-admin-password").exists()

    def test_bare_loopback_stays_open_with_setup(self, tmp_path, monkeypatch):
        """Bare loopback dev (no proxy) is not network-exposed => stay open."""
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "127.0.0.1")

        app = create_app()
        _drive_lifespan(app)

        from cert_watch.auth import NoAuthProvider

        assert isinstance(app.state.auth_provider, NoAuthProvider)
        assert app.state.needs_setup is True
        assert not (tmp_path / "initial-admin-password").exists()

    def test_allow_unauth_stays_open_on_nonloopback(self, tmp_path, monkeypatch):
        """CERT_WATCH_ALLOW_UNAUTH=1 forces open (no provision) on any bind."""
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "0.0.0.0")
        monkeypatch.setenv("CERT_WATCH_ALLOW_UNAUTH", "1")

        app = create_app()
        _drive_lifespan(app)

        from cert_watch.auth import NoAuthProvider

        assert isinstance(app.state.auth_provider, NoAuthProvider)
        assert not (tmp_path / "initial-admin-password").exists()

    def test_fails_closed_when_provisioning_fails_on_exposed_bind(self, tmp_path, monkeypatch):
        """If auto-provisioning can't persist an admin, an exposed bind refuses
        to serve open (fail-closed fallback)."""
        from cert_watch import app as app_mod
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "0.0.0.0")
        # Simulate provisioning that doesn't actually create an admin.
        monkeypatch.setattr(app_mod, "_provision_initial_admin", lambda s, **kw: None)

        app = create_app()
        with pytest.raises(SystemExit) as exc:
            _drive_lifespan(app)
        assert "0.0.0.0" in str(exc.value)

    def test_lifespan_starts_when_auth_configured_on_nonloopback(self, tmp_path, monkeypatch):
        """A real injected provider exempts the bind and skips provisioning."""
        from cert_watch.app import create_app
        from cert_watch.auth import LocalAdminProvider, _scrypt_hash

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "0.0.0.0")

        # Inject a real provider; the lifespan must not refuse to start.
        app = create_app(auth_provider=LocalAdminProvider("admin", _scrypt_hash("pw")))
        _drive_lifespan(app)
        assert not (tmp_path / "initial-admin-password").exists()

    def test_provision_initial_admin_writes_keys_atomically(self, tmp_path, monkeypatch):
        """_provision_initial_admin writes all kv_store keys (H3: password hash
        encrypted separately via kv_set_secret, the rest via kv_set_multi)."""
        from cert_watch.app import _provision_initial_admin
        from cert_watch.security import SecurityContext

        multi_calls = []
        secret_calls = []

        def _spy_multi(db_path, pairs):
            multi_calls.append(dict(pairs))
            kv_set_multi(db_path, pairs)

        def _spy_secret(db_path, key, value, enc_key):
            secret_calls.append((key, value))
            from cert_watch.database.kv_store import kv_set
            kv_set(db_path, key, value)

        monkeypatch.setattr("cert_watch.database.kv_store.kv_set_multi", _spy_multi)
        monkeypatch.setattr("cert_watch.database.kv_store.kv_set_secret", _spy_secret)

        db = tmp_path / "test.sqlite3"
        s = Settings(db_path=db, data_dir=tmp_path)
        security = SecurityContext(signing_key="test-secret", csrf_secret="test-csrf")
        _provision_initial_admin(s, security=security)

        # kv_set_multi carries the non-sensitive keys.
        assert len(multi_calls) == 1
        written = multi_calls[0]
        assert set(written.keys()) == {
            LOCAL_ADMIN_USER,
            LOCAL_ADMIN_AUTOGENERATED,
            SETUP_COMPLETE,
        }
        assert written[LOCAL_ADMIN_USER] == "admin"
        assert written[LOCAL_ADMIN_AUTOGENERATED] == "1"
        assert written[SETUP_COMPLETE] == "1"

        # kv_set_secret carries the password hash (H3: encrypted at rest).
        assert len(secret_calls) == 1
        assert secret_calls[0][0] == LOCAL_ADMIN_PASSWORD_HASH
        assert secret_calls[0][1]

        # Values actually persisted.
        rows = kv_all(db)
        assert rows[LOCAL_ADMIN_USER] == "admin"
        assert rows[LOCAL_ADMIN_AUTOGENERATED] == "1"
        assert rows[SETUP_COMPLETE] == "1"
        assert rows[LOCAL_ADMIN_PASSWORD_HASH]

    def test_provision_initial_admin_no_persist_on_file_write_failure(self, tmp_path, monkeypatch):
        """If the password file can't be written, kv_set_multi must NOT be called
        — the admin is not half-provisioned (WI-090). The lifespan fail-closed
        path handles the rest."""
        from cert_watch.app import _provision_initial_admin
        from cert_watch.security import SecurityContext

        called = []
        monkeypatch.setattr(
            "cert_watch.database.kv_store.kv_set_multi",
            lambda *a, **kw: called.append(a),
        )

        db = tmp_path / "test.sqlite3"
        s = Settings(db_path=db, data_dir=tmp_path)

        # Simulate an unwritable password file (e.g. full disk, bad perms).
        monkeypatch.setattr(
            "pathlib.Path.write_text", lambda *a, **kw: (_ for _ in ()).throw(OSError("disk full"))
        )

        security = SecurityContext(signing_key="test-secret", csrf_secret="test-csrf")
        _provision_initial_admin(s, security=security)

        # kv_set_multi was never called — no admin persisted.
        assert called == []
        # SETUP_COMPLETE was not written to the DB.
        from cert_watch.database.kv_store import kv_get
        assert kv_get(db, "setup_complete") is None
