"""Tests for HTML form-based API-key management routes (WI-044).

Covers routes in ``routes/settings/api_keys.py``: GET/POST /settings/api-keys
and POST /settings/api-keys/{key_id}/revoke.  The JSON /api/api-keys CRUD
routes are tested in ``test_api_keys.py``; this file covers the form-based
paths (admin-gate redirects, CSRF, validation, audit records).
"""

from __future__ import annotations

import json

from fastapi.testclient import TestClient

from cert_watch.database import init_schema
from cert_watch.database.api_keys import SqliteApiKeyRepository
from cert_watch.database.connection import _connect


def _seed_local_admin(tmp_path, autogenerated="1"):
    from cert_watch.auth import _scrypt_hash
    from cert_watch.database import kv_set

    db = tmp_path / "cert-watch.sqlite3"
    init_schema(db)
    kv_set(db, "local_admin_user", "admin")
    kv_set(db, "local_admin_password_hash", _scrypt_hash("testpassword"))
    kv_set(db, "local_admin_autogenerated", autogenerated)
    kv_set(db, "setup_complete", "1")
    return db


def _login_admin(client, monkeypatch):
    import cert_watch.middleware as mw
    import cert_watch.routes.auth as auth_routes

    monkeypatch.setattr(mw, "_COOKIE_SECURE", False)
    monkeypatch.setattr(auth_routes, "_COOKIE_SECURE", False)

    from starlette.requests import Request as StRequest

    from cert_watch.auth import SESSION_COOKIE, create_session
    from cert_watch.middleware import _request_security

    scope = {
        "type": "http",
        "method": "GET",
        "path": "/",
        "query_string": b"",
        "headers": [],
        "app": client.app,
        "session": {},
    }
    req = StRequest(scope)
    security = _request_security(req)
    token = create_session("admin", security, version=0)
    client.cookies.set(SESSION_COOKIE, token)
    return client


def _read_audit_rows(db_path):
    with _connect(db_path) as conn:
        rows = conn.execute(
            "SELECT actor, action, target_type, target_id, detail, source_ip"
            " FROM audit_log ORDER BY id DESC"
        ).fetchall()
    return [dict(r) for r in rows]


# ---------- GET /settings/api-keys ----------


def test_get_api_keys_authenticated_admin_redirects(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.get("/settings/api-keys", follow_redirects=False)
    assert r.status_code == 303
    assert r.headers["location"] == "/settings?tab=api-keys"


def test_get_api_keys_unauthenticated_redirects_to_login(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        r = client.get("/settings/api-keys", follow_redirects=False)
    assert r.status_code == 303
    assert "/login" in r.headers["location"]


def test_get_api_keys_non_admin_redirected_via_route(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    _seed_local_admin(tmp_path)
    monkeypatch.setenv("CERT_WATCH_ROLE_MAP", '{"viewer": {"groups": ["viewers"], "roles": []}}')
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.get("/settings/api-keys", follow_redirects=False)
    assert r.status_code == 303
    assert "admin+required" in r.headers["location"] or "admin%20required" in r.headers["location"]


# ---------- POST /settings/api-keys (create) ----------


def test_create_api_key_happy_path(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            "/settings/api-keys",
            data={"name": "deploy-key", "scope": "write"},
            follow_redirects=False,
        )
    assert r.status_code == 200
    assert "deploy-key" in r.text
    assert "cwk_" in r.text

    repo = SqliteApiKeyRepository(db)
    keys = repo.list_keys()
    assert len(keys) == 1
    assert keys[0].name == "deploy-key"
    assert keys[0].scope == "write"
    assert keys[0].revoked is False

    rows = _read_audit_rows(db)
    assert len(rows) >= 1
    audit = rows[0]
    assert audit["actor"] == "admin"
    assert audit["action"] == "api_key.create"
    assert audit["target_type"] == "api_key"
    assert audit["target_id"] == keys[0].id
    detail = json.loads(audit["detail"])
    assert detail["name"] == "deploy-key"
    assert detail["scope"] == "write"
    # Security property: the raw token must never appear in the audit row.
    assert "cwk_" not in audit["detail"]
    assert audit["source_ip"] is not None


def test_create_api_key_raw_token_shown_once(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            "/settings/api-keys",
            data={"name": "ci", "scope": "read"},
            follow_redirects=False,
        )
    assert r.status_code == 200
    assert 'data-testid="api-key-token"' in r.text


def test_create_api_key_empty_name(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            "/settings/api-keys",
            data={"name": "", "scope": "read"},
            follow_redirects=False,
        )
    assert r.status_code == 200
    assert "A name is required" in r.text

    repo = SqliteApiKeyRepository(db)
    assert len(repo.list_keys()) == 0
    rows = _read_audit_rows(db)
    assert not any(r["action"] == "api_key.create" for r in rows)


def test_create_api_key_csrf_error_does_not_mutate_db(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.delenv("CERT_WATCH_CSRF_DISABLED", raising=False)
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            "/settings/api-keys",
            data={"name": "csrf-leak", "scope": "read"},
            follow_redirects=False,
        )
    assert r.status_code == 200
    assert "CSRF" in r.text or "csrf" in r.text.lower() or "missing" in r.text.lower()
    # Guards against a mutate-then-check-CSRF reordering bug.
    repo = SqliteApiKeyRepository(db)
    assert len(repo.list_keys()) == 0
    rows = _read_audit_rows(db)
    assert not any(r["action"] == "api_key.create" for r in rows)


def test_create_api_key_whitespace_name(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            "/settings/api-keys",
            data={"name": "   ", "scope": "read"},
            follow_redirects=False,
        )
    assert r.status_code == 200
    assert "A name is required" in r.text
    repo = SqliteApiKeyRepository(db)
    assert len(repo.list_keys()) == 0


def test_create_api_key_invalid_scope(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            "/settings/api-keys",
            data={"name": "bad-scope-key", "scope": "superuser"},
            follow_redirects=False,
        )
    assert r.status_code == 200
    assert "Invalid scope" in r.text
    repo = SqliteApiKeyRepository(db)
    assert len(repo.list_keys()) == 0


def test_create_api_key_default_scope_is_read(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            "/settings/api-keys",
            data={"name": "default-scope"},
            follow_redirects=False,
        )
    assert r.status_code == 200
    repo = SqliteApiKeyRepository(db)
    keys = repo.list_keys()
    assert len(keys) == 1
    assert keys[0].scope == "read"


def test_create_api_key_admin_gate(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    _seed_local_admin(tmp_path)
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        r = client.post(
            "/settings/api-keys",
            data={"name": "noauth", "scope": "read"},
            follow_redirects=False,
        )
    assert r.status_code == 303
    assert "/login" in r.headers["location"]


def test_create_api_key_non_admin_redirected(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    _seed_local_admin(tmp_path)
    monkeypatch.setenv("CERT_WATCH_ROLE_MAP", '{"viewer": {"groups": ["viewers"], "roles": []}}')
    app_mod = reload_app()
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            "/settings/api-keys",
            data={"name": "noadmin", "scope": "read"},
            follow_redirects=False,
        )
    assert r.status_code == 303
    assert "admin+required" in r.headers["location"] or "admin%20required" in r.headers["location"]


# ---------- POST /settings/api-keys/{key_id}/revoke ----------


def test_revoke_api_key_happy_path(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()

    repo = SqliteApiKeyRepository(db)
    entry, raw_token = repo.create_key("to-revoke", "admin")

    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            f"/settings/api-keys/{entry.id}/revoke",
            follow_redirects=False,
        )
    assert r.status_code == 303
    assert "api-keys" in r.headers["location"]

    assert repo.verify_key(raw_token) is None

    rows = _read_audit_rows(db)
    assert len(rows) >= 1
    audit = rows[0]
    assert audit["actor"] == "admin"
    assert audit["action"] == "api_key.revoke"
    assert audit["target_type"] == "api_key"
    assert audit["target_id"] == entry.id


def test_revoke_api_key_unknown_key_id(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()

    fake_id = "a" * 32
    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            f"/settings/api-keys/{fake_id}/revoke",
            follow_redirects=False,
        )
    assert r.status_code == 303
    assert "api-keys" in r.headers["location"]

    rows = _read_audit_rows(db)
    revoke_rows = [r for r in rows if r["action"] == "api_key.revoke"]
    assert len(revoke_rows) == 1
    assert revoke_rows[0]["target_id"] == fake_id


def test_revoke_api_key_csrf_error(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.delenv("CERT_WATCH_CSRF_DISABLED", raising=False)
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()

    repo = SqliteApiKeyRepository(db)
    entry, _ = repo.create_key("csrf-revoke", "read")

    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            f"/settings/api-keys/{entry.id}/revoke",
            follow_redirects=False,
        )
    assert r.status_code == 200
    assert "CSRF" in r.text or "csrf" in r.text.lower() or "missing" in r.text.lower()
    # Guards against a revoke-then-check-CSRF reordering bug.
    assert repo.list_keys()[0].revoked is False


def test_revoke_api_key_admin_gate(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()

    repo = SqliteApiKeyRepository(db)
    entry, _ = repo.create_key("still-alive", "read")

    with TestClient(app_mod.app) as client:
        r = client.post(
            f"/settings/api-keys/{entry.id}/revoke",
            follow_redirects=False,
        )
    assert r.status_code == 303
    assert "/login" in r.headers["location"]

    assert repo.list_keys()[0].revoked is False


def test_revoke_api_key_non_admin_redirected(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    monkeypatch.setenv("CERT_WATCH_ROLE_MAP", '{"viewer": {"groups": ["viewers"], "roles": []}}')
    app_mod = reload_app()

    repo = SqliteApiKeyRepository(db)
    entry, _ = repo.create_key("still-alive2", "read")

    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        r = client.post(
            f"/settings/api-keys/{entry.id}/revoke",
            follow_redirects=False,
        )
    assert r.status_code == 303
    assert "admin+required" in r.headers["location"] or "admin%20required" in r.headers["location"]
    assert repo.list_keys()[0].revoked is False


def test_revoke_api_key_audit_source_ip_populated(reload_app, tmp_path, monkeypatch):
    monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
    monkeypatch.setenv("CERT_WATCH_CSRF_DISABLED", "1")
    db = _seed_local_admin(tmp_path)
    app_mod = reload_app()

    repo = SqliteApiKeyRepository(db)
    entry, _ = repo.create_key("ip-check", "read")

    with TestClient(app_mod.app) as client:
        _login_admin(client, monkeypatch)
        client.post(
            f"/settings/api-keys/{entry.id}/revoke",
            follow_redirects=False,
        )

    rows = _read_audit_rows(db)
    revoke_rows = [r for r in rows if r["action"] == "api_key.revoke"]
    assert len(revoke_rows) == 1
    assert revoke_rows[0]["source_ip"] is not None
