"""Tests for BC-083 (secure-by-default) and BC-081 (session revocation)."""

from __future__ import annotations

import asyncio
import os
import sqlite3
from unittest.mock import patch

import pytest
from fastapi.testclient import TestClient

from cert_watch.auth import (
    LocalAdminProvider,
    NoAuthProvider,
    create_session,
    set_signing_key,
    validate_session,
)
from cert_watch.config import (
    LOCAL_ADMIN_AUTOGENERATED,
    LOCAL_ADMIN_PASSWORD_HASH,
    LOCAL_ADMIN_USER,
    SETUP_COMPLETE,
    Settings,
)
from cert_watch.database import init_schema, kv_get, kv_set
from cert_watch.database.kv_store import kv_all, kv_set_multi
from cert_watch.database.queries import bump_session_version, get_session_version
from cert_watch.middleware import set_csrf_secret

# ---------- BC-083: Secure-by-default auth posture ----------


def _drive_lifespan(app) -> None:
    """Enter and cleanly exit the app's real lifespan once.

    Exercises the actual ``cert_watch.app`` startup path (BC-083 check,
    scheduler start/stop) rather than re-implementing its boolean. Raises
    whatever the lifespan raises (e.g. SystemExit).
    """

    async def _run() -> None:
        async with app.router.lifespan_context(app):
            pass

    asyncio.run(_run())


def _clean_env(monkeypatch, tmp_path) -> None:
    """Strip ambient auth/host config so each test controls the inputs."""
    for var in (
        "AUTH_PROVIDER",
        "CERT_WATCH_ALLOW_UNAUTH",
        "CERT_WATCH_HOST",
        "CERT_WATCH_TRUST_PROXY",
        "CERT_WATCH_AUTH_SECRET",
        "CERT_WATCH_CSRF_SECRET",
        "CERT_WATCH_LOCAL_ADMIN_USER",
        "CERT_WATCH_LOCAL_ADMIN_PASSWORD_HASH",
    ):
        monkeypatch.delenv(var, raising=False)
    monkeypatch.setenv("CERT_WATCH_DATA_DIR", str(tmp_path))


class TestBC083SecureByDefault:
    """Drive the *real* lifespan (cert_watch.app) — not a replica of its boolean.
    First-run posture: a network-exposed instance with no auth auto-provisions a
    local admin (comes up authenticated); bare loopback dev stays open + /setup;
    ALLOW_UNAUTH forces open; provisioning failure on an exposed bind fails closed."""

    def test_autoprovisions_admin_on_nonloopback_no_auth(self, tmp_path, monkeypatch):
        """No auth + routable bind => auto-provision a local admin and start."""
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "0.0.0.0")

        app = create_app()
        _drive_lifespan(app)  # must not raise

        assert isinstance(app.state.auth_provider, LocalAdminProvider)
        assert not isinstance(app.state.auth_provider, NoAuthProvider)
        assert kv_get(tmp_path / "cert-watch.sqlite3", "local_admin_user") == "admin"
        assert kv_get(tmp_path / "cert-watch.sqlite3", "local_admin_autogenerated") == "1"
        assert (tmp_path / "initial-admin-password").exists()

    def test_autoprovisions_behind_proxy_on_loopback(self, tmp_path, monkeypatch):
        """Loopback + TRUST_PROXY=1 (IIS/nginx) is network-exposed => provision."""
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "127.0.0.1")
        monkeypatch.setenv("CERT_WATCH_TRUST_PROXY", "1")

        app = create_app()
        _drive_lifespan(app)

        assert isinstance(app.state.auth_provider, LocalAdminProvider)
        assert (tmp_path / "initial-admin-password").exists()

    def test_bare_loopback_stays_open_with_setup(self, tmp_path, monkeypatch):
        """Bare loopback dev (no proxy) is not network-exposed => stay open."""
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "127.0.0.1")

        app = create_app()
        _drive_lifespan(app)

        assert isinstance(app.state.auth_provider, NoAuthProvider)
        assert app.state.needs_setup is True
        assert not (tmp_path / "initial-admin-password").exists()

    def test_allow_unauth_stays_open_on_nonloopback(self, tmp_path, monkeypatch):
        """CERT_WATCH_ALLOW_UNAUTH=1 forces open (no provision) on any bind."""
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "0.0.0.0")
        monkeypatch.setenv("CERT_WATCH_ALLOW_UNAUTH", "1")

        app = create_app()
        _drive_lifespan(app)

        assert isinstance(app.state.auth_provider, NoAuthProvider)
        assert not (tmp_path / "initial-admin-password").exists()

    def test_fails_closed_when_provisioning_fails_on_exposed_bind(self, tmp_path, monkeypatch):
        """If auto-provisioning can't persist an admin, an exposed bind refuses
        to serve open (fail-closed fallback)."""
        from cert_watch import app as app_mod
        from cert_watch.app import create_app

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "0.0.0.0")
        # Simulate provisioning that doesn't actually create an admin.
        monkeypatch.setattr(app_mod, "_provision_initial_admin", lambda s: None)

        app = create_app()
        with pytest.raises(SystemExit) as exc:
            _drive_lifespan(app)
        assert "0.0.0.0" in str(exc.value)

    def test_lifespan_starts_when_auth_configured_on_nonloopback(self, tmp_path, monkeypatch):
        """A real injected provider exempts the bind and skips provisioning."""
        from cert_watch.app import create_app
        from cert_watch.auth import _scrypt_hash

        _clean_env(monkeypatch, tmp_path)
        monkeypatch.setenv("CERT_WATCH_HOST", "0.0.0.0")

        # Inject a real provider; the lifespan must not refuse to start.
        app = create_app(auth_provider=LocalAdminProvider("admin", _scrypt_hash("pw")))
        _drive_lifespan(app)
        assert not (tmp_path / "initial-admin-password").exists()

    def test_provision_initial_admin_writes_keys_atomically(self, tmp_path, monkeypatch):
        """_provision_initial_admin must write all four kv_store keys in a single
        kv_set_multi call so the first-run admin cannot be left half-provisioned."""
        from cert_watch.app import _provision_initial_admin

        calls = []

        def _spy(db_path, pairs):
            calls.append(dict(pairs))
            kv_set_multi(db_path, pairs)

        monkeypatch.setattr("cert_watch.database.kv_store.kv_set_multi", _spy)

        db = tmp_path / "test.sqlite3"
        s = Settings(db_path=db, data_dir=tmp_path)
        _provision_initial_admin(s)

        # Atomicity: exactly one multi-set call carried all four keys.
        assert len(calls) == 1
        written = calls[0]
        assert set(written.keys()) == {
            LOCAL_ADMIN_USER,
            LOCAL_ADMIN_PASSWORD_HASH,
            LOCAL_ADMIN_AUTOGENERATED,
            SETUP_COMPLETE,
        }
        assert written[LOCAL_ADMIN_USER] == "admin"
        assert written[LOCAL_ADMIN_AUTOGENERATED] == "1"
        assert written[SETUP_COMPLETE] == "1"
        assert written[LOCAL_ADMIN_PASSWORD_HASH]

        # Values actually persisted.
        rows = kv_all(db)
        assert rows[LOCAL_ADMIN_USER] == "admin"
        assert rows[LOCAL_ADMIN_AUTOGENERATED] == "1"
        assert rows[SETUP_COMPLETE] == "1"
        assert rows[LOCAL_ADMIN_PASSWORD_HASH]

    def test_provision_initial_admin_no_persist_on_file_write_failure(self, tmp_path, monkeypatch):
        """If the password file can't be written, kv_set_multi must NOT be called
        — the admin is not half-provisioned (WI-090). The lifespan fail-closed
        path handles the rest."""
        from cert_watch.app import _provision_initial_admin

        called = []
        monkeypatch.setattr(
            "cert_watch.database.kv_store.kv_set_multi",
            lambda *a, **kw: called.append(a),
        )

        db = tmp_path / "test.sqlite3"
        s = Settings(db_path=db, data_dir=tmp_path)

        # Simulate an unwritable password file (e.g. full disk, bad perms).
        monkeypatch.setattr(
            "pathlib.Path.write_text", lambda *a, **kw: (_ for _ in ()).throw(OSError("disk full"))
        )

        _provision_initial_admin(s)

        # kv_set_multi was never called — no admin persisted.
        assert called == []
        # SETUP_COMPLETE was not written to the DB.
        from cert_watch.database.kv_store import kv_get
        assert kv_get(db, "setup_complete") is None


class TestEntrypointHostNormalization:
    """BC-090: __main__ is the single source of truth for the bind host — it
    normalizes CERT_WATCH_HOST to what it passes to uvicorn, so the BC-083
    check (which reads that env var) can never diverge from the real bind."""

    def test_host_arg_normalizes_env(self, monkeypatch):
        """`--host 127.0.0.1` sets CERT_WATCH_HOST=127.0.0.1 (the IIS path)."""
        from cert_watch.__main__ import main

        monkeypatch.delenv("CERT_WATCH_HOST", raising=False)
        with patch("uvicorn.run") as run:
            main(["--host", "127.0.0.1", "--port", "12345"])

        assert os.environ["CERT_WATCH_HOST"] == "127.0.0.1"
        _, kwargs = run.call_args
        assert kwargs["host"] == "127.0.0.1"
        assert kwargs["port"] == 12345
        # main() writes CERT_WATCH_HOST to os.environ directly (BC-090).
        # monkeypatch.delenv is a no-op when the var was absent, so the
        # direct write isn't tracked for undo.  Clean up to prevent the
        # loopback value from leaking into later tests (e.g. the BC-083
        # compliance auth-gate test would see network_exposed=False →
        # SERVE_OPEN → NoAuthProvider → 200 instead of 401).
        os.environ.pop("CERT_WATCH_HOST", None)

    def test_host_arg_overrides_env(self, monkeypatch):
        """--host wins over a pre-set CERT_WATCH_HOST."""
        from cert_watch.__main__ import main

        monkeypatch.setenv("CERT_WATCH_HOST", "0.0.0.0")
        with patch("uvicorn.run") as run:
            main(["--host", "127.0.0.1"])

        assert os.environ["CERT_WATCH_HOST"] == "127.0.0.1"
        assert run.call_args.kwargs["host"] == "127.0.0.1"

    def test_default_host_falls_back_to_env_then_default(self, monkeypatch):
        """No --host: use CERT_WATCH_HOST if set, else 0.0.0.0."""
        from cert_watch.__main__ import main

        monkeypatch.setenv("CERT_WATCH_HOST", "10.0.0.5")
        with patch("uvicorn.run") as run:
            main([])
        assert run.call_args.kwargs["host"] == "10.0.0.5"

        monkeypatch.delenv("CERT_WATCH_HOST", raising=False)
        with patch("uvicorn.run") as run:
            main([])
        assert run.call_args.kwargs["host"] == "0.0.0.0"
        assert os.environ["CERT_WATCH_HOST"] == "0.0.0.0"


# ---------- BC-081: Server-side session revocation ----------


class TestBC081SessionRevocation:
    """Tests for per-user session version tracking (BC-081)."""

    def test_get_session_version_default(self, tmp_path):
        """A user with no row in session_versions has version 0."""
        db = tmp_path / "test.sqlite3"
        init_schema(db)
        version = get_session_version(db, "nonexistent")
        assert version == 0

    def test_bump_creates_row(self, tmp_path):
        """bump_session_version creates a row starting at version 1."""
        db = tmp_path / "test.sqlite3"
        init_schema(db)
        version = bump_session_version(db, "alice")
        assert version == 1

        # Row exists in DB
        with sqlite3.connect(str(db)) as conn:
            row = conn.execute(
                "SELECT version FROM session_versions WHERE username = ?", ("alice",)
            ).fetchone()
        assert row is not None
        assert row[0] == 1

    def test_bump_increments(self, tmp_path):
        """Subsequent bumps increment the version."""
        db = tmp_path / "test.sqlite3"
        init_schema(db)
        v1 = bump_session_version(db, "alice")
        v2 = bump_session_version(db, "alice")
        v3 = bump_session_version(db, "alice")
        assert v1 == 1
        assert v2 == 2
        assert v3 == 3

    def test_session_with_version_valid(self, tmp_path):
        """A session token with the current version is valid."""
        db = tmp_path / "test.sqlite3"
        init_schema(db)
        set_signing_key("test-key-bc081")
        # Create a session with version=1 and ensure it validates
        bump_session_version(db, "alice")
        token = create_session("alice", version=1)
        result = validate_session(token, db_path=str(db))
        assert result == "alice"

    def test_session_with_old_version_invalid(self, tmp_path):
        """A session token with an old version is invalid after bump."""
        db = tmp_path / "test.sqlite3"
        init_schema(db)
        set_signing_key("test-key-bc081")
        # Create session at version 0 (before any bumps)
        token = create_session("alice", version=0)
        # Bump the session version to 1 (simulating logout)
        bump_session_version(db, "alice")
        # Old token should be invalid
        result = validate_session(token, db_path=str(db))
        assert result is None

    def test_session_without_db_path_backward_compat(self):
        """Without db_path, version checking is skipped (backward compat for
        unit tests that don't have a database)."""
        set_signing_key("test-key-bc081-compat")
        token = create_session("alice", version=0)
        # Should validate fine without a DB check
        result = validate_session(token)
        assert result == "alice"

    def test_new_session_after_bump_valid(self, tmp_path):
        """After a bump, a newly issued session with the new version is valid."""
        db = tmp_path / "test.sqlite3"
        init_schema(db)
        set_signing_key("test-key-bc081-new")
        bump_session_version(db, "alice")
        # Create token with current version
        token = create_session("alice", version=1)
        result = validate_session(token, db_path=str(db))
        assert result == "alice"

    def test_logout_bumps_version(self, tmp_path, monkeypatch):
        """POST /auth/logout bumps the session version for the logged-in user."""
        monkeypatch.setenv("CERT_WATCH_AUTH_SECRET", "test-logout-key")
        monkeypatch.setenv("CERT_WATCH_CSRF_SECRET", "test-logout-csrf")
        monkeypatch.setenv("CERT_WATCH_COOKIE_SECURE", "0")
        # Patch module-level _COOKIE_SECURE so the cookie is sent over HTTP
        import cert_watch.routes.auth as auth_routes
        monkeypatch.setattr(auth_routes, "_COOKIE_SECURE", False)
        set_signing_key("test-logout-key")
        set_csrf_secret("test-logout-csrf")

        from cert_watch.app import create_app
        from cert_watch.auth import LocalAdminProvider, _scrypt_hash
        from cert_watch.config import Settings
        from cert_watch.security import SecurityContext

        db = tmp_path / "test.sqlite3"
        init_schema(db)
        # Set up a local admin
        kv_set(db, "local_admin_user", "admin")
        kv_set(db, "local_admin_password_hash", _scrypt_hash("password123"))
        kv_set(db, "setup_complete", "1")

        s = Settings(
            db_path=db,
            data_dir=tmp_path,
            auth_provider="local",
            local_admin_user="admin",
            local_admin_password_hash=_scrypt_hash("password123"),
            allow_unauth=False,
        )
        auth = LocalAdminProvider("admin", _scrypt_hash("password123"))
        security = SecurityContext(signing_key="test-logout-key", csrf_secret="test-logout-csrf")
        app = create_app(settings=s, auth_provider=auth, security=security)
        with TestClient(app) as client:
            # Log in to get a session
            response = client.post("/login", data={
                "username": "admin",
                "password": "password123",
            }, follow_redirects=False)
            assert response.status_code == 303

            # The session version for admin should be >=1 after login (BC-029 D)
            ver_before = get_session_version(db, "admin")
            assert ver_before >= 1

            # Now log out — should bump the session version.
            # Note: CSRF is disabled by the autouse conftest fixture.
            response = client.post("/auth/logout", follow_redirects=False)
            assert response.status_code == 303

            # After logout, the session version should be bumped
            ver_after = get_session_version(db, "admin")
            assert ver_after > ver_before

    def test_old_session_token_invalidated_after_logout(self, tmp_path):
        """After logout bumps version, old session tokens are rejected."""
        db = tmp_path / "test.sqlite3"
        init_schema(db)
        set_signing_key("test-revoke-key")

        # Create session at version 0
        token_old = create_session("bob", version=0)
        # Session should be valid (version 0 <= stored version 0)
        assert validate_session(token_old, db_path=str(db)) == "bob"

        # Simulate logout: bump version to 1
        bump_session_version(db, "bob")
        # Old token (version 0) should now be invalid
        assert validate_session(token_old, db_path=str(db)) is None

        # New token at version 1 should be valid
        token_new = create_session("bob", version=1)
        assert validate_session(token_new, db_path=str(db)) == "bob"

    def test_migration_creates_session_versions_table(self, tmp_path):
        """Migration 0011 creates the session_versions table."""
        db = tmp_path / "test.sqlite3"
        init_schema(db)
        with sqlite3.connect(str(db)) as conn:
            tables = {r[0] for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).fetchall()}
        assert "session_versions" in tables

    def test_multiple_users_independent(self, tmp_path):
        """Bumping one user's version doesn't affect another user's sessions."""
        db = tmp_path / "test.sqlite3"
        init_schema(db)
        set_signing_key("test-multi-key")

        # Both users start at version 0
        token_alice = create_session("alice", version=0)
        token_bob = create_session("bob", version=0)

        # Both valid before any bumps
        assert validate_session(token_alice, db_path=str(db)) == "alice"
        assert validate_session(token_bob, db_path=str(db)) == "bob"

        # Bump alice's version (logout)
        bump_session_version(db, "alice")

        # Alice's old token invalid, bob's still valid
        assert validate_session(token_alice, db_path=str(db)) is None
        assert validate_session(token_bob, db_path=str(db)) == "bob"
