apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-watch-data
  namespace: cert-watch
  labels:
    app.kubernetes.io/name: cert-watch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
