"""cert-watch configuration — re-exported from the decomposed package.

Decomposed from the monolithic config.py (BC-144a / config decomposition).
All imports remain backward-compatible: ``from cert_watch.config import Settings``
works exactly as before.
"""

from cert_watch.config.field_specs import (
    FIELD_SPECS,
    SENSITIVE_SETTING_KEYS,
    FieldSpec,
    _default_data_dir_str,
)
from cert_watch.config.helpers import (
    _default_data_dir,
    _parse_float,
    _parse_int,
    _parse_role_map,
    _validate_range,
    read_secret,
    resolve_or_persist_secret,
    split_group_dns,
)
from cert_watch.config.kv_loader import (
    LOCAL_ADMIN_AUTOGENERATED,
    LOCAL_ADMIN_PASSWORD_HASH,
    LOCAL_ADMIN_USER,
    SETUP_COMPLETE,
)
from cert_watch.config.loader import setting_env_is_set, setting_env_source, ui_field_map
from cert_watch.config.runtime import (
    current_settings,
    invalidate_settings,
    publish_settings,
    resolve_and_publish_settings,
    settings_generation,
)
from cert_watch.config.settings import Settings

__all__ = [
    "FIELD_SPECS",
    "LOCAL_ADMIN_AUTOGENERATED",
    "LOCAL_ADMIN_PASSWORD_HASH",
    "LOCAL_ADMIN_USER",
    "SENSITIVE_SETTING_KEYS",
    "SETUP_COMPLETE",
    "FieldSpec",
    "Settings",
    "_default_data_dir",
    "_default_data_dir_str",
    "_parse_float",
    "_parse_int",
    "_parse_role_map",
    "_validate_range",
    "current_settings",
    "invalidate_settings",
    "publish_settings",
    "read_secret",
    "resolve_and_publish_settings",
    "resolve_or_persist_secret",
    "setting_env_is_set",
    "setting_env_source",
    "settings_generation",
    "split_group_dns",
    "ui_field_map",
]
