"""kv_store-aware Settings loader: merges GUI-configured values into env base.

Decomposed from the monolithic config.py (BC-144a / config decomposition).
"""

from __future__ import annotations

import logging
from dataclasses import fields, replace
from pathlib import Path

from cert_watch.config.loader import merge_kv_values
from cert_watch.config.settings import Settings

logger = logging.getLogger("cert_watch.config.kv_loader")

LOCAL_ADMIN_USER = "local_admin_user"
LOCAL_ADMIN_PASSWORD_HASH = "local_admin_password_hash"
LOCAL_ADMIN_AUTOGENERATED = "local_admin_autogenerated"
SETUP_COMPLETE = "setup_complete"


def _merge_kv_settings(
    base: Settings, db_path: Path, encryption_key: str | None = None,
) -> Settings:
    """Merge kv_store values into a base Settings object.

    Returns a new Settings instance.  Env vars take precedence over kv_store.
    """
    if not db_path:
        return base
    try:
        from cert_watch.database import kv_all
        kv = kv_all(db_path)
    except Exception:
        logger.warning("kv_store load failed; using env-only settings", exc_info=True)
        return base
    if not kv:
        return base

    base_values = {item.name: getattr(base, item.name) for item in fields(base)}
    merged = merge_kv_values(
        base_values,
        kv,
        encryption_key=encryption_key,
    )
    return replace(base, **merged)
