"""Local admin password rotation route."""

from __future__ import annotations

import logging
import os
from pathlib import Path

from fastapi import APIRouter, Request
from fastapi.responses import RedirectResponse

from cert_watch.auth import _scrypt_hash, verify_scrypt_hash
from cert_watch.config import (
    LOCAL_ADMIN_AUTOGENERATED,
    LOCAL_ADMIN_PASSWORD_HASH,
    LOCAL_ADMIN_USER,
)
from cert_watch.database import bump_session_version, get_write_lock, kv_get, kv_set, kv_set_secret
from cert_watch.middleware import check_csrf, require_admin_form
from cert_watch.routes._deps import _db_path, _get_settings
from cert_watch.routes.settings.core import _rebuild_settings

logger = logging.getLogger("cert_watch.routes.settings")

router = APIRouter()


@router.post("/settings/change-password")
async def change_local_admin_password(request: Request) -> RedirectResponse:
    admin_err = require_admin_form(request)
    if admin_err:
        return admin_err

    csrf_err = await check_csrf(request)
    if csrf_err:
        return RedirectResponse(url=f"/settings?tab=auth&error={csrf_err}", status_code=303)

    db = _db_path(request)
    s = _get_settings(request)
    form = await request.form()

    _cur = form.get("current_password") or ""
    _new = form.get("new_password") or ""
    _conf = form.get("confirm_password") or ""
    current_password = _cur.strip() if isinstance(_cur, str) else ""
    new_password = _new.strip() if isinstance(_new, str) else ""
    confirm_password = _conf.strip() if isinstance(_conf, str) else ""

    if not current_password or not new_password:
        return RedirectResponse(
            url="/settings?tab=auth&error=current+and+new+password+are+required", status_code=303
        )
    if len(current_password) > 1024:
        return RedirectResponse(
            url="/settings?tab=auth&error=current+password+too+long", status_code=303,
        )
    if len(new_password) < 8:
        return RedirectResponse(
            url="/settings?tab=auth&error=new+password+must+be+at+least+8+characters",
            status_code=303,
        )
    if len(new_password) > 1024:
        return RedirectResponse(
            url="/settings?tab=auth&error=new+password+must+not+exceed+1024+characters",
            status_code=303,
        )
    if new_password != confirm_password:
        return RedirectResponse(
            url="/settings?tab=auth&error=new+passwords+do+not+match", status_code=303
        )

    env_hash = os.environ.get("CERT_WATCH_LOCAL_ADMIN_PASSWORD_HASH", "").strip()
    if env_hash:
        return RedirectResponse(
            url="/settings?tab=auth&error=cannot+rotate+via+UI:+CERT_WATCH_LOCAL_ADMIN_PASSWORD_HASH+is+set+(env+always+wins)",
            status_code=303,
        )

    # H3: decrypt the stored hash if it was encrypted at rest
    from cert_watch.routes.settings.config import _get_encryption_key

    enc_key = _get_encryption_key(request)
    stored_hash = kv_get(db, LOCAL_ADMIN_PASSWORD_HASH, encryption_key=enc_key) or ""
    if not stored_hash:
        return RedirectResponse(
            url="/settings?tab=auth&error=no+local+admin+password+hash+found", status_code=303
        )

    if not verify_scrypt_hash(current_password, stored_hash):
        return RedirectResponse(
            url="/settings?tab=auth&error=current+password+is+incorrect", status_code=303
        )

    # H3: persist the new hash encrypted at rest
    new_hash = _scrypt_hash(new_password)
    with get_write_lock():
        if enc_key:
            kv_set_secret(db, LOCAL_ADMIN_PASSWORD_HASH, new_hash, enc_key)
        else:
            kv_set(db, LOCAL_ADMIN_PASSWORD_HASH, new_hash)
        kv_set(db, LOCAL_ADMIN_AUTOGENERATED, "0")

    # Invalidate all existing sessions for this user
    username = kv_get(db, LOCAL_ADMIN_USER) or "admin"
    bump_session_version(db, username)

    # Delete the one-time password file if it still exists
    _clear_initial_password_file(s.data_dir)

    # Rebuild auth provider with new hash
    _rebuild_settings(request, db)
    _security = getattr(request.app.state, "security", None)
    auth = _get_settings(request).build_auth_provider(security=_security)
    request.app.state.auth_provider = auth

    logger.info("Local admin password rotated via UI")
    return RedirectResponse(url="/settings?tab=auth&password_changed=1", status_code=303)


def _clear_initial_password_file(data_dir: Path) -> None:
    try:
        pw_file = data_dir / "initial-admin-password"
        if pw_file.exists():
            pw_file.unlink()
            logger.info("Deleted initial-admin-password file after rotation")
    except OSError:
        logger.debug("Could not delete initial-admin-password file", exc_info=True)
