"""Local admin password rotation route."""

from __future__ import annotations

import logging
import os
from pathlib import Path

from fastapi import APIRouter, Request
from fastapi.responses import RedirectResponse

from cert_watch.auth import _scrypt_hash, verify_scrypt_hash
from cert_watch.database import kv_get, kv_set
from cert_watch.database.queries import bump_session_version
from cert_watch.middleware import check_csrf, require_admin_form
from cert_watch.routes._deps import _db_path, _get_settings
from cert_watch.routes.settings.core import _rebuild_settings

logger = logging.getLogger("cert_watch.routes.settings")

router = APIRouter()


@router.post("/settings/change-password")
async def change_local_admin_password(request: Request) -> RedirectResponse:
    admin_err = require_admin_form(request)
    if admin_err:
        return admin_err

    csrf_err = await check_csrf(request)
    if csrf_err:
        return RedirectResponse(url=f"/settings?tab=auth&error={csrf_err}", status_code=303)

    db = _db_path(request)
    s = _get_settings(request)
    form = await request.form()

    _cur = form.get("current_password") or ""
    _new = form.get("new_password") or ""
    _conf = form.get("confirm_password") or ""
    current_password = _cur.strip() if isinstance(_cur, str) else ""
    new_password = _new.strip() if isinstance(_new, str) else ""
    confirm_password = _conf.strip() if isinstance(_conf, str) else ""

    if not current_password or not new_password:
        return RedirectResponse(
            url="/settings?tab=auth&error=current+and+new+password+are+required", status_code=303
        )
    if len(new_password) < 8:
        return RedirectResponse(
            url="/settings?tab=auth&error=new+password+must+be+at+least+8+characters",
            status_code=303,
        )
    if new_password != confirm_password:
        return RedirectResponse(
            url="/settings?tab=auth&error=new+passwords+do+not+match", status_code=303
        )

    env_hash = os.environ.get("CERT_WATCH_LOCAL_ADMIN_PASSWORD_HASH", "").strip()
    if env_hash:
        return RedirectResponse(
            url="/settings?tab=auth&error=cannot+rotate+via+UI:+CERT_WATCH_LOCAL_ADMIN_PASSWORD_HASH+is+set+(env+always+wins)",
            status_code=303,
        )

    stored_hash = kv_get(db, "local_admin_password_hash") or ""
    if not stored_hash:
        return RedirectResponse(
            url="/settings?tab=auth&error=no+local+admin+password+hash+found", status_code=303
        )

    if not verify_scrypt_hash(current_password, stored_hash):
        return RedirectResponse(
            url="/settings?tab=auth&error=current+password+is+incorrect", status_code=303
        )

    # Persist new hash + clear autogenerated flag
    kv_set(db, "local_admin_password_hash", _scrypt_hash(new_password))
    kv_set(db, "local_admin_autogenerated", "0")

    # Invalidate all existing sessions for this user
    username = kv_get(db, "local_admin_user") or "admin"
    bump_session_version(db, username)

    # Delete the one-time password file if it still exists
    _clear_initial_password_file(s.data_dir)

    # Rebuild auth provider with new hash
    _rebuild_settings(request, db)
    auth = _get_settings(request).build_auth_provider()
    request.app.state.auth_provider = auth

    logger.info("Local admin password rotated via UI")
    return RedirectResponse(url="/settings?tab=auth&password_changed=1", status_code=303)


def _clear_initial_password_file(data_dir: Path) -> None:
    try:
        pw_file = data_dir / "initial-admin-password"
        if pw_file.exists():
            pw_file.unlink()
            logger.info("Deleted initial-admin-password file after rotation")
    except OSError:
        logger.debug("Could not delete initial-admin-password file", exc_info=True)
