"""Settings page rendering helpers and shared template context."""

from __future__ import annotations

import json

from fastapi import Request
from fastapi.responses import HTMLResponse

from cert_watch import __commit__, __version__
from cert_watch.config import LOCAL_ADMIN_AUTOGENERATED, LOCAL_ADMIN_USER
from cert_watch.database import ApiKeyEntry, kv_get
from cert_watch.middleware import get_auth_context, get_csrf_context
from cert_watch.routes._deps import _db_path, get_templates
from cert_watch.routes.settings.config import (
    _ALERT_KEYS,
    _AUTH_KEYS,
    _SMTP_KEYS,
    _effective_config,
    _env_overrides,
    _get_encryption_key,
)

templates = get_templates()


def _local_admin_configured(request: Request) -> bool:
    """Return True if a local admin account exists in kv_store."""
    db = _db_path(request)
    return bool(kv_get(db, LOCAL_ADMIN_USER))


def _settings_context(
    request: Request,
    *,
    tab: str = "auth",
    saved: str | None = None,
    error: str | None = None,
    password_changed: str | None = None,
    new_token: str | None = None,
    new_name: str | None = None,
) -> dict:
    """Build the full context dict for ``settings.html``.

    Used by ``settings_page()`` and ``_render_api_keys()`` so both render the
    same template with identical chrome (tabs, nav, auth config, etc.).
    """
    import os

    from cert_watch.config import SENSITIVE_SETTING_KEYS

    db = _db_path(request)
    enc_key = _get_encryption_key(request)
    auth_config = _effective_config(_AUTH_KEYS, db, enc_key)
    smtp_config = _effective_config(_SMTP_KEYS, db, enc_key)
    alert_config = _effective_config(_ALERT_KEYS, db, enc_key)
    env_overrides = {
        **_env_overrides(_AUTH_KEYS, db),
        **_env_overrides(_SMTP_KEYS, db),
        **_env_overrides(_ALERT_KEYS, db),
    }
    display_config = {}
    for k, v in {**auth_config, **smtp_config, **alert_config}.items():
        if k in SENSITIVE_SETTING_KEYS and v:
            display_config[k] = "••••••••"
        else:
            display_config[k] = v

    local_admin = _local_admin_configured(request)
    env_hash_override = bool(os.environ.get("CERT_WATCH_LOCAL_ADMIN_PASSWORD_HASH", "").strip())
    autogenerated = local_admin and kv_get(db, LOCAL_ADMIN_AUTOGENERATED) == "1"

    ldap_role_map_raw = kv_get(db, "ldap_role_map") or "{}"
    try:
        ldap_role_map = json.loads(ldap_role_map_raw)
    except (json.JSONDecodeError, TypeError):
        ldap_role_map = {}

    roles_data: list = []
    users_data: list = []
    alert_groups_data: list = []
    if tab in ("roles", "users"):
        from cert_watch.database import SqliteRoleRepository, SqliteUserRepository
        roles_data = SqliteRoleRepository(db).list_all()
        users_data = SqliteUserRepository(db).list_all()
        if tab == "roles":
            from cert_watch.database import SqliteAlertGroupRepository
            alert_groups_data = SqliteAlertGroupRepository(db).list_all()
    elif tab == "auth":
        from cert_watch.database import SqliteRoleRepository
        roles_data = SqliteRoleRepository(db).list_all()

    api_keys_data: list[ApiKeyEntry] = []
    if tab == "api-keys":
        from cert_watch.database import SqliteApiKeyRepository
        api_keys_data = SqliteApiKeyRepository(db).list_keys()

    policy_set = None
    if tab == "policy":
        from cert_watch.policy import load_policy_set
        policy_set = load_policy_set(str(db))

    auth_ctx = get_auth_context(request)
    csrf_ctx = get_csrf_context(request)
    return {
        "version": __version__, "commit": __commit__,
        "tab": tab,
        "saved": saved,
        "error": error,
        "password_changed": password_changed,
        "auth": display_config,
        "smtp": display_config,
        "alert": display_config,
        "env_overrides": env_overrides,
        "local_admin_configured": local_admin,
        "local_admin_autogenerated": autogenerated,
        "env_hash_override": env_hash_override,
        "ldap_role_map": ldap_role_map,
        "api_keys": api_keys_data,
        "policy_set": policy_set,
        "roles": roles_data,
        "users": users_data,
        "alert_groups": alert_groups_data,
        "active_page": "settings",
        "new_token": new_token,
        "new_name": new_name,
        **auth_ctx,
        **csrf_ctx,
    }


def _render_api_keys(
    request: Request,
    *,
    new_token: str | None = None,
    new_name: str | None = None,
    error: str | None = None,
) -> HTMLResponse:
    """Render the API-keys management page inside the settings chrome.

    ``new_token`` is shown exactly once.  Uses ``settings.html`` (tab=api-keys)
    so the settings tabs remain visible — the old ``api_keys.html`` standalone
    template is no longer used here.
    """
    return templates.TemplateResponse(
        request=request,
        name="settings.html",
        context=_settings_context(
            request,
            tab="api-keys",
            new_token=new_token,
            new_name=new_name,
            error=error,
        ),
    )
