"""Settings page rendering helpers and shared template context."""

from __future__ import annotations

import json
from typing import Any

from fastapi import Request
from fastapi.responses import HTMLResponse

from cert_watch import __commit__, __version__
from cert_watch.alert_adapters import WEBHOOK_KIND_OPTIONS
from cert_watch.config import LOCAL_ADMIN_AUTOGENERATED, LOCAL_ADMIN_USER
from cert_watch.database import ApiKeyEntry, kv_get
from cert_watch.middleware import get_auth_context, get_csrf_context
from cert_watch.routes._deps import _db_path, get_templates
from cert_watch.routes.settings.config import (
    _ALERT_KEYS,
    _AUTH_KEYS,
    _SMTP_KEYS,
    _effective_config,
    _env_overrides,
    _get_encryption_key,
)

templates = get_templates()


def _local_admin_configured(request: Request) -> bool:
    """Return True if a local admin account exists in kv_store."""
    db = _db_path(request)
    return bool(kv_get(db, LOCAL_ADMIN_USER))


def _settings_context(
    request: Request,
    *,
    tab: str = "auth",
    saved: str | None = None,
    error: str | None = None,
    password_changed: str | None = None,
    new_token: str | None = None,
    new_name: str | None = None,
) -> dict[str, Any]:
    """Build the full context dict for ``settings.html``.

    Used by ``settings_page()`` and ``_render_api_keys()`` so both render the
    same template with identical chrome (tabs, nav, auth config, etc.).
    """
    import os

    from cert_watch.config import SENSITIVE_SETTING_KEYS

    db = _db_path(request)
    enc_key = _get_encryption_key(request)
    auth_config = _effective_config(_AUTH_KEYS, db, enc_key)
    smtp_config = _effective_config(_SMTP_KEYS, db, enc_key)
    alert_config = _effective_config(_ALERT_KEYS, db, enc_key)
    env_overrides = {
        **_env_overrides(_AUTH_KEYS, db),
        **_env_overrides(_SMTP_KEYS, db),
        **_env_overrides(_ALERT_KEYS, db),
    }
    display_config = {}
    for k, v in {**auth_config, **smtp_config, **alert_config}.items():
        if k in SENSITIVE_SETTING_KEYS and v:
            display_config[k] = "••••••••"
        else:
            display_config[k] = v

    local_admin = _local_admin_configured(request)
    env_hash_override = bool(os.environ.get("CERT_WATCH_LOCAL_ADMIN_PASSWORD_HASH", "").strip())
    autogenerated = local_admin and kv_get(db, LOCAL_ADMIN_AUTOGENERATED) == "1"

    ldap_role_map_raw = kv_get(db, "ldap_role_map") or "{}"
    try:
        ldap_role_map = json.loads(ldap_role_map_raw)
    except (json.JSONDecodeError, TypeError):
        ldap_role_map = {}

    roles_data: list[Any] = []
    users_data: list[Any] = []
    alert_groups_data: list[Any] = []
    role_tag_tiers: dict[str, dict[str, str]] = {}
    if tab in ("roles", "users"):
        from cert_watch.database import SqliteRoleRepository, SqliteUserRepository
        role_repo = SqliteRoleRepository(db)
        roles_data = role_repo.list_all()
        users_data = SqliteUserRepository(db).list_all()
        role_tag_tiers = role_repo.all_tag_tiers()
        if tab == "roles":
            from cert_watch.database import SqliteAlertGroupRepository
            alert_groups_data = SqliteAlertGroupRepository(db).list_all()
    elif tab == "auth":
        from cert_watch.database import SqliteRoleRepository
        roles_data = SqliteRoleRepository(db).list_all()

    api_keys_data: list[ApiKeyEntry] = []
    if tab == "api-keys":
        from cert_watch.database import SqliteApiKeyRepository
        api_keys_data = SqliteApiKeyRepository(db).list_keys()

    policy_set = None
    if tab == "policy":
        from cert_watch.policy import load_policy_set
        policy_set = load_policy_set(str(db))

    trust_anchors: list[Any] = []
    if tab == "trust-anchors":
        from cert_watch.database import SqliteTrustAnchorRepository
        trust_anchors = SqliteTrustAnchorRepository(db).list_entries()

    tag_registry: list[dict[str, Any]] = []
    if tab == "tags":
        tag_registry = _build_tag_registry(db)

    auth_ctx = get_auth_context(request)
    csrf_ctx = get_csrf_context(request)
    return {
        "version": __version__, "commit": __commit__,
        "tab": tab,
        "saved": saved,
        "error": error,
        "password_changed": password_changed,
        "auth": display_config,
        "smtp": display_config,
        "alert": display_config,
        "env_overrides": env_overrides,
        "local_admin_configured": local_admin,
        "local_admin_autogenerated": autogenerated,
        "env_hash_override": env_hash_override,
        "ldap_role_map": ldap_role_map,
        "api_keys": api_keys_data,
        "policy_set": policy_set,
        "roles": roles_data,
        "users": users_data,
        "role_tag_tiers": role_tag_tiers,
        "alert_groups": alert_groups_data,
        "trust_anchors": trust_anchors,
        "tag_registry": tag_registry,
        "active_page": "settings",
        "new_token": new_token,
        "new_name": new_name,
        "webhook_kind_options": WEBHOOK_KIND_OPTIONS,
        **auth_ctx,
        **csrf_ctx,
    }


# One template per settings section (the settings.html monolith rendered
# all nine panels on every request and hid eight with CSS).
SECTION_TEMPLATES: dict[str, str] = {
    "auth": "settings/auth.html",
    "channels": "settings/channels.html",
    "alert-groups": "settings/alert_groups.html",
    "events": "settings/events.html",
    "policy": "settings/policy.html",
    "roles": "settings/roles.html",
    "users": "settings/users.html",
    "api-keys": "settings/api_keys.html",
    "tags": "settings/tags.html",
    "trust-anchors": "settings/trust_anchors.html",
}

# Old ?tab= names → canonical section slugs (smtp and alerts merged).
LEGACY_TAB_MAP: dict[str, str] = {
    "auth": "auth",
    "smtp": "channels",
    "alerts": "channels",
    "policy": "policy",
    "api-keys": "api-keys",
    "roles": "roles",
    "users": "users",
    "alert-groups": "alert-groups",
    "events": "events",
}


def _render_settings(
    request: Request,
    tab: str,
    **extra: Any,
) -> HTMLResponse:
    """Render one settings section with the shared context."""
    template = SECTION_TEMPLATES.get(tab, SECTION_TEMPLATES["auth"])
    ctx = _settings_context(request, tab=tab, **extra)
    return templates.TemplateResponse(request=request, name=template, context=ctx)


def _build_tag_registry(db: Any) -> list[dict[str, Any]]:
    """Every tag in use, with what it labels, scopes, and routes.

    Tags are simultaneously labels, access boundaries (role scopes /
    per-tag tiers), and alert-routing selectors — renaming one silently
    changes access and routing, so the registry shows all three facets.
    """
    from cert_watch.database import (
        SqliteAlertGroupRepository,
        SqliteRoleRepository,
        _connect,
    )
    from cert_watch.tags import parse_tags

    host_counts: dict[str, int] = {}
    cert_counts: dict[str, int] = {}
    with _connect(db) as conn:
        for row in conn.execute("SELECT tags FROM hosts WHERE tags != ''"):
            for t in parse_tags(row["tags"]):
                host_counts[t] = host_counts.get(t, 0) + 1
        for row in conn.execute(
            "SELECT tags FROM certificates WHERE tags != '' AND is_leaf = 1"
        ):
            for t in parse_tags(row["tags"]):
                cert_counts[t] = cert_counts.get(t, 0) + 1

    role_repo = SqliteRoleRepository(db)
    overrides = role_repo.all_tag_tiers()
    roles_by_tag: dict[str, list[dict[str, str]]] = {}
    for role in role_repo.list_all():
        for t in parse_tags(role.scope_tag):
            tier = overrides.get(role.id, {}).get(t, role.permission_tier)
            roles_by_tag.setdefault(t, []).append({"name": role.name, "tier": tier})

    groups_by_tag: dict[str, list[str]] = {}
    for grp in SqliteAlertGroupRepository(db).list_all():
        for t in parse_tags(getattr(grp, "match_tags", "") or ""):
            groups_by_tag.setdefault(t, []).append(grp.name)

    all_tags = sorted(
        set(host_counts) | set(cert_counts) | set(roles_by_tag) | set(groups_by_tag)
    )
    return [
        {
            "tag": t,
            "hosts": host_counts.get(t, 0),
            "certs": cert_counts.get(t, 0),
            "roles": roles_by_tag.get(t, []),
            "groups": groups_by_tag.get(t, []),
        }
        for t in all_tags
    ]


def _render_api_keys(
    request: Request,
    *,
    new_token: str | None = None,
    new_name: str | None = None,
    error: str | None = None,
) -> HTMLResponse:
    """Render the API-keys management page inside the settings chrome.

    ``new_token`` is shown exactly once.
    """
    return _render_settings(
        request,
        "api-keys",
        new_token=new_token,
        new_name=new_name,
        error=error,
    )
