"""FastAPI application factory with route auto-discovery.

THIS FILE IS FROZEN. Implementing agents MUST NOT modify this file.
Route modules are auto-discovered from routes/ directory.
"""

import importlib
import pkgutil
from pathlib import Path

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from ..core.config import Settings
from ..core.exceptions import CertWatchError


def create_app(settings: Settings | None = None) -> FastAPI:
    """Create and configure the FastAPI application.

    This function auto-discovers and registers all route modules.
    Implementing agents create new files in routes/ - they do NOT edit this file.

    Args:
        settings: Application settings (uses Settings.get() if None)

    Returns:
        Configured FastAPI application
    """
    if settings is None:
        settings = Settings.get()

    app = FastAPI(
        title=settings.app_name,
        description="TLS certificate monitoring dashboard",
        version="0.1.0",
        debug=settings.debug,
    )

    # Auto-discover and register routes
    _register_routes(app)

    # Register exception handlers
    _register_exception_handlers(app)

    # Serve static files if directory exists
    static_dir = Path(__file__).parent / "static"
    if static_dir.exists():
        app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")

    return app


def _register_routes(app: FastAPI) -> None:
    """Auto-discover and register route modules.

    Scans the routes/ directory for modules and registers any APIRouter
    instances named 'router'.
    """
    from . import routes

    routes_dir = Path(routes.__file__).parent

    for module_info in pkgutil.iter_modules([str(routes_dir)]):
        # Skip private modules (starting with underscore)
        if module_info.name.startswith("_"):
            continue

        # Import the module
        module = importlib.import_module(f"{routes.__name__}.{module_info.name}")

        # Look for 'router' attribute (APIRouter instance)
        if hasattr(module, "router"):
            router = module.router
            app.include_router(router)


def _register_exception_handlers(app: FastAPI) -> None:
    """Register exception handlers."""

    @app.exception_handler(CertWatchError)
    async def cert_watch_error_handler(request, exc: CertWatchError):
        from fastapi.responses import JSONResponse

        return JSONResponse(
            status_code=400,
            content={"error": type(exc).__name__, "detail": str(exc)},
        )
